### ISSUE TITLE
DASH generateStaticMpd method working not properly

### ISSUE THREAD

**Issue by kfeng0806** [aminyazdanpanah/shaka-php#12]
Since shaka-packager renamed flag `--generate_static_mpd` to` --generate_static_live_mpd` from version `v2.4.0`

The method `$options->generateStaticMpd()` no longer working anymore

**Comment by aminyazdanpanah** [comment]
Thank you for the report. I have just fixed the bug and now you can update the package:

``` bash
composer update aminyazdanpanah/php-shaka
```
