### ISSUE TITLE
streamSelector(0) is ignored

### ISSUE THREAD

**Issue by gregoriopellegrino** [aminyazdanpanah/shaka-php#15]
**Describe the bug**
I realized that if I assign to **streamSelector** the **zero** value (0), this is ignored in the command for packager, which does not report any information about the stream to select.

**To Reproduce**
1. Set streamSelector to zero, for example:
```
HLSStream::input($source_file)
	->streamSelector(0)
	->initSegment($output_path . 'video/init.mp4')
	->segmentTemplate($output_path . 'video/$Number$.m4s')
	->playlistName('video/main.m3u8')
	->iframeplaylistName('video/iframe.m3u8')
```
2. Run the script
3. The code generates the error `2 (Misuse of shell builtins)`
4. Analyzing the bug log you can see that there is no information about the stream in the command:
```
'./packager-osx' 'in=test.mp4,playlist_name=video/main.m3u8,iframe_playlist_name=video/iframe.m3u8,stream=1,init_segment=video/init.mp4,segment_template=video/$Number$.m4s'
```

**Expected behavior**
Enter the stream information in the command, for example:
```
'./packager-osx' 'in=test.mp4,playlist_name=video/main.m3u8,iframe_playlist_name=video/iframe.m3u8,stream=1,stream=0,init_segment=video/init.mp4,segment_template=video/$Number$.m4s'
```

**Comment by gregoriopellegrino** [comment]
I think I have found the line to modify.

- File: `src/Options/Streams/Stream.php`
- Line: `80`
- Change: `if (!$this->stream_selector) {`
- To: `if (!isset($this->stream_selector)) {`

**Comment by aminyazdanpanah** [comment]
Thank you for the report. I have just fixed the bug and now you can update the package:

```bash
composer update aminyazdanpanah/php-shaka
```
