### ISSUE TITLE
Exit Code: 1(General error)

### ISSUE THREAD

**Issue by RV8395** [aminyazdanpanah/shaka-php#3]
i'm using linux server and getting error of Exit Code: 1(General error) because of packager .exe file
How do i need give path of exe file while using linux server because in my local windows server it is working fine.

**Comment by aminyazdanpanah** [comment]
`.exe` is an executable file for DOS, OpenVMS, Microsoft Windows, Symbian or OS/2. You cannot use it in Unix / Linux Environment. 

Instead, you should use the binary that it has been built for Linux.
Try these commands in your Linux terminal:


1.
``` bash
sudo wget https://github.com/google/shaka-packager/releases/download/v2.3.0/packager-linux
```
2.
``` bash
sudo chmod +x packager-linux
```
3.
``` bash
sudo mv packager-linux /usr/bin/packager
```

**Comment by RV8395** [comment]
okay thank you but then what should i give path in this particular code Shaka::initialize('PATH') ? do i need to point out /bin/packager ?

**Comment by aminyazdanpanah** [comment]
If the `/usr/bin/` directory has been added to the system path then you do not have to pass the 'packager' path to the `initialize` method (Shaka-PHP autodetects the 'packager' binary).

Otherwise, you need to pass the binary path to the method:

``` php
$shaka = Shaka\Shaka::initialize('/usr/bin/packager');
```

**Comment by RV8395** [comment]
okay thank you

**Comment by RV8395** [comment]
Now i got vps and got sudo access and i did manage to install shaka-packager on linux hosting and also now i'm able to find file but now i'm getting exit code 1 error again as below can you please guide me with this issue ?

ERROR:

The command "'/bin/packager' 'in=/home/studygurueducati/public_html/sgadmin/public/uploads/lessons/2_1566032973.mp4,stream=audio,init_segment=/home/studygurueducati/public_html/sgadmin/public/output/2_1566032973/audio/init.mp4,segment_template=/home/studygurueducati/public_html/sgadmin/public/output/2_1566032973/audio/$Number$.m4s' 'in=/home/studygurueducati/public_html/sgadmin/public/uploads/lessons/2_1566032973.mp4,stream=video,init_segment=/home/studygurueducati/public_html/sgadmin/public/output/2_1566032973/video/init.mp4,segment_template=/home/studygurueducati/public_html/sgadmin/public/output/2_1566032973/video/$Number$.m4s' '--enable_widevine_encryption' '--key_server_url' 'https://license.uat.widevine.com/cenc/getcontentkey/widevine_test' '--content_id' 'KEY' '--signer' 'widevine_test' '--aes_signing_key' 'KEY' '--aes_signing_iv' 'KEY' '--mpd_output' '/home/studygurueducati/public_html/sgadmin/public/output/2_1566032973/output.mpd'" failed. ◀

Exit Code: 1(General error)

Working directory: /home/studygurueducati/public_html/sgadmin/public
