### ISSUE TITLE
EXIT CODE: 1 error

### ISSUE THREAD

**Issue by RV8395** [aminyazdanpanah/shaka-php#4]
Now i got vps and got sudo access and i did manage to install shaka-packager on linux hosting and also now i'm able to find file but now i'm getting exit code 1 error again as below can you please guide me with this issue ?

ERROR:

The command "'/bin/packager' 'in=/home/studygurueducati/public_html/sgadmin/public/uploads/lessons/2_1566032973.mp4,stream=audio,init_segment=/home/studygurueducati/public_html/sgadmin/public/output/2_1566032973/audio/init.mp4,segment_template=/home/studygurueducati/public_html/sgadmin/public/output/2_1566032973/audio/$Number$.m4s' 'in=/home/studygurueducati/public_html/sgadmin/public/uploads/lessons/2_1566032973.mp4,stream=video,init_segment=/home/studygurueducati/public_html/sgadmin/public/output/2_1566032973/video/init.mp4,segment_template=/home/studygurueducati/public_html/sgadmin/public/output/2_1566032973/video/$Number$.m4s' '--enable_widevine_encryption' '--key_server_url' 'https://license.uat.widevine.com/cenc/getcontentkey/widevine_test' '--content_id' 'KEY' '--signer' 'widevine_test' '--aes_signing_key' 'KEY' '--aes_signing_iv' 'KEY' '--mpd_output' '/home/studygurueducati/public_html/sgadmin/public/output/2_1566032973/output.mpd'" failed. ◀

Exit Code: 1(General error)

Working directory: /home/studygurueducati/public_html/sgadmin/public

**Comment by aminyazdanpanah** [comment]
It seems your `Widevine` license is not valid. Please read the `Widevine` document found **[here](https://www.widevine.com/solutions/widevine-drm)**. 

If you believe that your `Widevine` license and keys are valid, please **[contact them](https://www.widevine.com/contact)** to help with that. I don't have any control over it, sorry!

**NOTE:** Please **DO NOT** post your private information such as `Widevine` license and keys in the public forum.

**Comment by RV8395** [comment]
okay thank you
