### ISSUE TITLE
Process timeout

### ISSUE THREAD

**Issue by kfeng0806** [aminyazdanpanah/shaka-php#7]
Hello,
I am facing `The process xxx exceeded the timeout of 60 seconds.` error when converting a long video.
The Symfony Process package has default timeout limit to 60s

**Comment by aminyazdanpanah** [comment]
Thank you for your reporting. I have just fixed [the bug](https://github.com/aminyazdanpanah/shaka-php/commit/943b0312032549ced7b62db793da40bc3ce57823) and now you can set the timeout of process. But before you get started, you must update the package:

``` bash
composer update aminyazdanpanah/php-shaka
```
After updating the package, you can pass an associative array of config to the `initialize` method:

``` php
$config = [
    'packager.binaries' => 'path/to/packager/binary',
    'timeout'           =>  3600
];

$shaka = \Shaka\Shaka::initialize($config);
```

**Comment by kfeng0806** [comment]
Thank you very much!
